source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'TLImageSpring_Example', :exclusive => true do
  pod 'TLImageSpring', :path => '../'
end

target 'TLImageSpring_Tests', :exclusive => true do
  pod 'TLImageSpring', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  # pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
